FROM python:3.9
WORKDIR /amazon-clone-flask
COPY ./server/* ./server
COPY ./requirements.txt . 
RUN pip3 install -r ./requirements.txt
EXPOSE 5000
WORKDIR /amazon-clone-flask/server
COPY ./entrypoint.sh .
ENTRYPOINT ["./entrypoint.sh"]
