FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_module/.bin:$PATH
COPY package.json package-lock.json /app
COPY ./src /app/src
COPY ./public /app/public
RUN npm install
CMD ["npm" , "start"]
